[package]
name = "language-server-rust"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
tokio = { version = "1.41.1", features = ["full"] }
tower-lsp-server = "0.21.0"
tracing-subscriber = "0.3.19"

[[bin]]
name = "server"
path = "src/server.rs"
